=== pxai/ozone/Data/etc/expert_system.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD of UESML: Universal Expert System Modelling Language -->
<!-- VERSION = 1.0 -->
<!-- 10/09/2001 -->
<!-- Inspired by Annette Truong -->

<!ELEMENT EXPERT_SYSTEM (EXPERT)>

	<!ELEMENT EXPERT (HEADER?,OBJECTS*,INSTANCES*,FUNCTIONS*, RULES*)>
	<!ATTLIST EXPERT
		NAME CDATA #REQUIRED
		VERSION CDATA #REQUIRED
	>
		<!-- HEADER DEFINITION-->
		<!ELEMENT HEADER (IMPORT*,GLOBALS*, MODULEDEF*)>
			<!-- import -->
			<!ELEMENT IMPORT  (PACKAGE+)>
				<!ELEMENT PACKAGE (#PCDATA)>		
			<!-- globals -->
			<!ELEMENT GLOBALS (GLOBAL+)>
				<!ELEMENT GLOBAL EMPTY>
				<!ATTLIST 	GLOBAL
						NAME CDATA #REQUIRED
						TYPE CDATA #REQUIRED
						VALUE CDATA #IMPLIED
				>
			<!-- moduledef -->
			<!ELEMENT MODULEDEF  (#PCDATA)>		

		<!-- OBJECT DEFINITION-->
		<!ELEMENT OBJECTS (OBJECT_DEFINITION)+>
			<!-- object_definition -->
			<!ELEMENT OBJECT_DEFINITION (ATTRIBUTES*)>	
				<!ATTLIST 	OBJECT_DEFINITION
					NAME CDATA #REQUIRED
					EXTENDS CDATA #REQUIRED
					IMPLEMENTS CDATA #REQUIRED
				>
				<!-- ATTRIBUTES -->
				<!ELEMENT ATTRIBUTES  EMPTY>
				<!ATTLIST 	ATTRIBUTES
					NAME CDATA #REQUIRED
					TYPE CDATA #REQUIRED
					VALUE CDATA #IMPLIED
					VISIBILITY (public | protected | private) #IMPLIED
				>
				
		<!-- INSTANCES -->
		<!ELEMENT INSTANCES  (INSTANCE+)>
			<!-- instance -->
				<!ELEMENT INSTANCE  (ATTR_VALUES*)>
				<!ATTLIST INSTANCE
					NAME CDATA #REQUIRED
					OBJECT CDATA #REQUIRED
				>		
				<!ELEMENT ATTR_VALUES EMPTY>
				<!ATTLIST ATTR_VALUES
					TYPE CDATA  #REQUIRED
					VALUE CDATA #REQUIRED
				>				
				
		<!-- FUNCTION DEFINITION-->
		<!ELEMENT FUNCTIONS (LOGIC+)>
			<!-- logic-->
			<!ELEMENT LOGIC (SENTENCE*,RETURN*) >
				<!ELEMENT SENTENCE (DEFVARIABLE* | EXPRESSION* | LOOP* | IF* | SWITCH* ) >
					<!ELEMENT DEFVARIABLE (VARIABLE+)>
						<!ELEMENT VARIABLE EMPTY>
						<!ATTLIST VARIABLE
							TYPE CDATA #REQUIRED
							NAME CDATA #REQUIRED
							VALUE CDATA #IMPLIED
						>				
					<!--- EXPRESSION -->
					<!ELEMENT EXPRESSION  ((VAR*, (SUBEXPRESSION)+) | CALL)>
						<!ELEMENT VAR (#PCDATA)>
						<!ELEMENT SUBEXPRESSION ( VAR | CALL | (SUBEXPRESSION*,OPERATOR?,SUBEXPRESSION*) )>
							<!ELEMENT OPERATOR EMPTY>
							<!ATTLIST OPERATOR
								OP CDATA #REQUIRED
							>				
					<!--- LOOP -->
					<!ELEMENT LOOP (CONDITION,SENTENCE*)>
						<!ELEMENT CONDITION  (#PCDATA)>
					<!--- IF -->
					<!ELEMENT IF  (CONDITION,SENTENCE+, (ELSIF* | ELSE?)?)>
						<!ELEMENT ELSIF (CONDITION,SENTENCE+)>
						<!ELEMENT ELSE (SENTENCE+)>
					<!--- SWITCH -->
					<!ELEMENT SWITCH  (#PCDATA)>
					<!--- CALL-->
					<!ELEMENT CALL  (PARAMETER*)>
						<!ELEMENT PARAMETER EMPTY>
						<!ATTLIST PARAMETER
							TYPE CDATA #REQUIRED
							VALUE CDATA #IMPLIED
						>				
					<!--- RETURN -->
					<!ELEMENT RETURN  (EXPRESSION)>
				
		<!-- RULES DEFINITION-->
		<!ELEMENT RULES (LHS*,RHS+)>
			<!-- lhs : left hand side of rule -->
			<!ELEMENT LHS (#PCDATA)>
			<!-- rhs : right hand side of rule -->
			<!ELEMENT RHS (#PCDATA)>

=== pxai/ozone/Data/etc/first_system.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE EXPERT_SYSTEM SYSTEM "expert_system.dtd">
<EXPERT_SYSTEM>
	<EXPERT NAME="first_system"  VERSION="1.0">
		<HEADER>
			<MODULEDEF>first_system</MODULEDEF>
		</HEADER>
		
		<!-- OBJECT DEFINITIONS -->
		<OBJECTS>
			<OBJECT_DEFINITION NAME="person" EXTENDS="" IMPLEMENTS="">
				<ATTRIBUTES NAME="name" TYPE="String" />
				<ATTRIBUTES NAME="age" TYPE="int" />
			</OBJECT_DEFINITION>
			<OBJECT_DEFINITION NAME="job" EXTENDS="" IMPLEMENTS="">
				<ATTRIBUTES NAME="name" TYPE="String" />
				<ATTRIBUTES NAME="salary" TYPE="float" />
			</OBJECT_DEFINITION>		
		</OBJECTS>
		
		<!-- INSTANCES -->
		<INSTANCES>			
			<INSTANCE  NAME="instance1" OBJECT="person" >
				<ATTR_VALUES VALUE="Pedro Alcazar" TYPE="String" />
				<ATTR_VALUES VALUE="23" TYPE="int" />				
			</INSTANCE>
			<INSTANCE  NAME="instance2" OBJECT="person" >
				<ATTR_VALUES VALUE="Robert de Niro" TYPE="String" />
				<ATTR_VALUES VALUE="61" TYPE="int" />				
			</INSTANCE>
			<INSTANCE  NAME="instance3" OBJECT="person" >
				<ATTR_VALUES VALUE="Al Pacino" TYPE="String" />
				<ATTR_VALUES VALUE="63" TYPE="int" />				
			</INSTANCE>
	   </INSTANCES>
	</EXPERT>
</EXPERT_SYSTEM>
