=== pxai/ozone/Data/etc/LOGIC.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT LOGIC (METHOD*)>
<!ELEMENT METHOD (PARAMETER*, RETURN?)>
<!ATTLIST METHOD
	NAME CDATA #REQUIRED
>
<!ELEMENT PARAMETER (#PCDATA)>
<!ATTLIST PARAMETER
	NAME CDATA #REQUIRED
	>
<!ELEMENT RETURN (#PCDATA)>

=== pxai/ozone/Data/etc/program1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LOGIC SYSTEM "logic.dtd">
<!-- Sample program -->
<LOGIC>
	<METHOD NAME="add">
		<PARAMETER NAME="param1">0</PARAMETER>
		<PARAMETER NAME="param2">0</PARAMETER>
	</METHOD>
	<METHOD NAME="sub">
		<PARAMETER NAME="param1">0</PARAMETER>
		<PARAMETER NAME="param2">0</PARAMETER>
	</METHOD>
	<METHOD NAME="div">
		<PARAMETER NAME="param1">0</PARAMETER>
		<PARAMETER NAME="param2">0</PARAMETER>
	</METHOD>
	<METHOD NAME="mul">
		<PARAMETER NAME="param1">0</PARAMETER>
		<PARAMETER NAME="param2">0</PARAMETER>
	</METHOD>
</LOGIC>
