=== pxai/ozone/Data/etc/properties.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- P. Al. -->
<!-- Generic properties file-->
<!ELEMENT PROPERTIES (PROPERTY*)>
<!ELEMENT PROPERTY (#PCDATA)>
<!ATTLIST PROPERTY
	NAME CDATA #REQUIRED
>

=== pxai/ozone/Data/etc/properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- INFeReNCZy system properties file -->
<!DOCTYPE PROPERTIES SYSTEM "properties.dtd">
<PROPERTIES>
	<PROPERTY NAME="system_version" >1.0.01</PROPERTY>
	<PROPERTY NAME="loglevel" >1</PROPERTY>
	<PROPERTY NAME="logfile" >Data/log/inferenczy.log</PROPERTY>
	<PROPERTY NAME="multiuser_y_n" >y</PROPERTY>
	<PROPERTY NAME="server_y_n" >y</PROPERTY>
	<PROPERTY NAME="language" >en</PROPERTY>
	<PROPERTY NAME="db_type" >sql</PROPERTY>
	<PROPERTY NAME="jdbc_driver" >sun.jdbc.odbc.JdbcOdbcDriver</PROPERTY>
	<PROPERTY NAME="jdbc_url" >jdbc:odbc:pruebas</PROPERTY>
	<PROPERTY NAME="jdbc_user" ></PROPERTY>
	<PROPERTY NAME="jdbc_password" ></PROPERTY>
	<PROPERTY NAME="init.d" >Data/etc/init.d</PROPERTY>
</PROPERTIES>
